services:
  python:
    build: .
    restart: always
    volumes:
      - ./:/app
      - ./pip.conf:/etc/pip.conf
    command:  sh -c "cd /app && pip install --upgrade pip && pip install -r requirements.txt && python -u main.py"
