services:
  python:
    image: python:3
    restart: always
    volumes:
      - ./main.py:/app/main.py
      - ./list_fritz.py:/app/list_fritz.py
      - ./requirements.txt:/app/requirements.txt
    command:  sh -c "cd /app && pip install --upgrade pip && pip install -r requirements.txt && python main.py"
